const countries: Record<string, string> = {
  Angola: "AO",
  Bolivia: "BO",
  Brazil: "BR",
  Burundi: "BI",
  Cameroon: "CM",
  "Central African Republic": "CF",
  China: "CN",
  Colombia: "CO",
  "Costa Rica": "CR",
  Cuba: "CU",
  "Côte d'Ivoire": "CI",
  "Democratic Republic of the Congo": "CD",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  "El Salvador": "SV",
  Ethiopia: "ET",
  Gabon: "GA",
  Ghana: "GH",
  Guatemala: "GT",
  Guinea: "GN",
  Haiti: "HT",
  Honduras: "HN",
  India: "IN",
  Indonesia: "ID",
  Jamaica: "JM",
  Kenya: "KE",
  Laos: "LA",
  Liberia: "LR",
  Madagascar: "MG",
  Malawi: "MW",
  Mexico: "MX",
  Nicaragua: "NI",
  Nigeria: "NG",
  Panama: "PA",
  "Papua New Guinea": "PG",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  Rwanda: "RW",
  "Sierra Leone": "SL",
  Thailand: "TH",
  "Timor-Leste": "TL",
  Togo: "TG",
  "Trinidad and Tobago": "TT",
  Uganda: "UG",
  "United Republic of Tanzania": "TZ",
  Venezuela: "VE",
  Vietnam: "VN",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
};

export default countries;
