/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ApiFeatureFlagsRouteImport } from './routes/api/feature-flags'
import { Route as ApiDecentShotsRouteImport } from './routes/api/decent-shots'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthLayoutFullRouteImport } from './routes/_auth/_layoutFull'
import { Route as AuthLayoutRouteImport } from './routes/_auth/_layout'
import { Route as AuthLayoutIndexRouteImport } from './routes/_auth/_layout/index'
import { Route as AuthLayoutSettingsRouteImport } from './routes/_auth/_layout/settings'
import { Route as AuthLayoutDesignLibraryRouteImport } from './routes/_auth/_layout/design-library'
import { Route as AuthLayoutDecentUploadRouteImport } from './routes/_auth/_layout/decent-upload'
import { Route as AuthLayoutAiRouteImport } from './routes/_auth/_layout/ai'
import { Route as AuthLayoutDrinksIndexRouteImport } from './routes/_auth/_layout/drinks/index'
import { Route as AuthLayoutBeansIndexRouteImport } from './routes/_auth/_layout/beans/index'
import { Route as AuthLayoutBeansAddRouteImport } from './routes/_auth/_layout/beans/add'
import { Route as AuthLayoutDrinksTastingsIndexRouteImport } from './routes/_auth/_layout/drinks/tastings/index'
import { Route as AuthLayoutDrinksEspressoIndexRouteImport } from './routes/_auth/_layout/drinks/espresso/index'
import { Route as AuthLayoutDrinksBrewsIndexRouteImport } from './routes/_auth/_layout/drinks/brews/index'
import { Route as AuthLayoutBeansBeansIdIndexRouteImport } from './routes/_auth/_layout/beans/$beansId/index'
import { Route as AuthLayoutFullDrinksBrewsTableRouteImport } from './routes/_auth/_layoutFull/drinks/brews/table'
import { Route as AuthLayoutDrinksTastingsTastingIdRouteImport } from './routes/_auth/_layout/drinks/tastings/$tastingId'
import { Route as AuthLayoutDrinksEspressoAddRouteImport } from './routes/_auth/_layout/drinks/espresso/add'
import { Route as AuthLayoutDrinksBrewsAddRouteImport } from './routes/_auth/_layout/drinks/brews/add'
import { Route as AuthLayoutBeansBeansIdEditRouteImport } from './routes/_auth/_layout/beans/$beansId/edit'
import { Route as AuthLayoutBeansBeansIdCloneRouteImport } from './routes/_auth/_layout/beans/$beansId/clone'
import { Route as AuthLayoutDrinksTastingsTastingIdIndexRouteImport } from './routes/_auth/_layout/drinks/tastings/$tastingId/index'
import { Route as AuthLayoutDrinksEspressoEspressoIdIndexRouteImport } from './routes/_auth/_layout/drinks/espresso/$espressoId/index'
import { Route as AuthLayoutDrinksBrewsBrewIdIndexRouteImport } from './routes/_auth/_layout/drinks/brews/$brewId/index'
import { Route as AuthLayoutDrinksEspressoEspressoIdOutcomeRouteImport } from './routes/_auth/_layout/drinks/espresso/$espressoId/outcome'
import { Route as AuthLayoutDrinksEspressoEspressoIdEditRouteImport } from './routes/_auth/_layout/drinks/espresso/$espressoId/edit'
import { Route as AuthLayoutDrinksEspressoEspressoIdCloneRouteImport } from './routes/_auth/_layout/drinks/espresso/$espressoId/clone'
import { Route as AuthLayoutDrinksBrewsBrewIdOutcomeRouteImport } from './routes/_auth/_layout/drinks/brews/$brewId/outcome'
import { Route as AuthLayoutDrinksBrewsBrewIdEditRouteImport } from './routes/_auth/_layout/drinks/brews/$brewId/edit'
import { Route as AuthLayoutDrinksBrewsBrewIdCloneRouteImport } from './routes/_auth/_layout/drinks/brews/$brewId/clone'
import { Route as AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRouteImport } from './routes/_auth/_layout/drinks/tastings/$tastingId/samples/$sampleId'
import { Route as AuthLayoutDrinksEspressoEspressoIdDecentEditRouteImport } from './routes/_auth/_layout/drinks/espresso/$espressoId/decent/edit'
import { Route as AuthLayoutDrinksEspressoEspressoIdDecentAddRouteImport } from './routes/_auth/_layout/drinks/espresso/$espressoId/decent/add'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeatureFlagsRoute = ApiFeatureFlagsRouteImport.update({
  id: '/api/feature-flags',
  path: '/api/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecentShotsRoute = ApiDecentShotsRouteImport.update({
  id: '/api/decent-shots',
  path: '/api/decent-shots',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any).lazy(() => import('./routes/_public/login.lazy').then((d) => d.Route))
const AuthLayoutFullRoute = AuthLayoutFullRouteImport.update({
  id: '/_layoutFull',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutIndexRoute = AuthLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSettingsRoute = AuthLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutDesignLibraryRoute = AuthLayoutDesignLibraryRouteImport.update({
  id: '/design-library',
  path: '/design-library',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutDecentUploadRoute = AuthLayoutDecentUploadRouteImport.update({
  id: '/decent-upload',
  path: '/decent-upload',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAiRoute = AuthLayoutAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutDrinksIndexRoute = AuthLayoutDrinksIndexRouteImport.update({
  id: '/drinks/',
  path: '/drinks/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutBeansIndexRoute = AuthLayoutBeansIndexRouteImport.update({
  id: '/beans/',
  path: '/beans/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutBeansAddRoute = AuthLayoutBeansAddRouteImport.update({
  id: '/beans/add',
  path: '/beans/add',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutDrinksTastingsIndexRoute =
  AuthLayoutDrinksTastingsIndexRouteImport.update({
    id: '/drinks/tastings/',
    path: '/drinks/tastings/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksEspressoIndexRoute =
  AuthLayoutDrinksEspressoIndexRouteImport.update({
    id: '/drinks/espresso/',
    path: '/drinks/espresso/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksBrewsIndexRoute =
  AuthLayoutDrinksBrewsIndexRouteImport.update({
    id: '/drinks/brews/',
    path: '/drinks/brews/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutBeansBeansIdIndexRoute =
  AuthLayoutBeansBeansIdIndexRouteImport.update({
    id: '/beans/$beansId/',
    path: '/beans/$beansId/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutFullDrinksBrewsTableRoute =
  AuthLayoutFullDrinksBrewsTableRouteImport.update({
    id: '/drinks/brews/table',
    path: '/drinks/brews/table',
    getParentRoute: () => AuthLayoutFullRoute,
  } as any)
const AuthLayoutDrinksTastingsTastingIdRoute =
  AuthLayoutDrinksTastingsTastingIdRouteImport.update({
    id: '/drinks/tastings/$tastingId',
    path: '/drinks/tastings/$tastingId',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksEspressoAddRoute =
  AuthLayoutDrinksEspressoAddRouteImport.update({
    id: '/drinks/espresso/add',
    path: '/drinks/espresso/add',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksBrewsAddRoute =
  AuthLayoutDrinksBrewsAddRouteImport.update({
    id: '/drinks/brews/add',
    path: '/drinks/brews/add',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutBeansBeansIdEditRoute =
  AuthLayoutBeansBeansIdEditRouteImport.update({
    id: '/beans/$beansId/edit',
    path: '/beans/$beansId/edit',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutBeansBeansIdCloneRoute =
  AuthLayoutBeansBeansIdCloneRouteImport.update({
    id: '/beans/$beansId/clone',
    path: '/beans/$beansId/clone',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksTastingsTastingIdIndexRoute =
  AuthLayoutDrinksTastingsTastingIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthLayoutDrinksTastingsTastingIdRoute,
  } as any)
const AuthLayoutDrinksEspressoEspressoIdIndexRoute =
  AuthLayoutDrinksEspressoEspressoIdIndexRouteImport.update({
    id: '/drinks/espresso/$espressoId/',
    path: '/drinks/espresso/$espressoId/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksBrewsBrewIdIndexRoute =
  AuthLayoutDrinksBrewsBrewIdIndexRouteImport.update({
    id: '/drinks/brews/$brewId/',
    path: '/drinks/brews/$brewId/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksEspressoEspressoIdOutcomeRoute =
  AuthLayoutDrinksEspressoEspressoIdOutcomeRouteImport.update({
    id: '/drinks/espresso/$espressoId/outcome',
    path: '/drinks/espresso/$espressoId/outcome',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksEspressoEspressoIdEditRoute =
  AuthLayoutDrinksEspressoEspressoIdEditRouteImport.update({
    id: '/drinks/espresso/$espressoId/edit',
    path: '/drinks/espresso/$espressoId/edit',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksEspressoEspressoIdCloneRoute =
  AuthLayoutDrinksEspressoEspressoIdCloneRouteImport.update({
    id: '/drinks/espresso/$espressoId/clone',
    path: '/drinks/espresso/$espressoId/clone',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksBrewsBrewIdOutcomeRoute =
  AuthLayoutDrinksBrewsBrewIdOutcomeRouteImport.update({
    id: '/drinks/brews/$brewId/outcome',
    path: '/drinks/brews/$brewId/outcome',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksBrewsBrewIdEditRoute =
  AuthLayoutDrinksBrewsBrewIdEditRouteImport.update({
    id: '/drinks/brews/$brewId/edit',
    path: '/drinks/brews/$brewId/edit',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksBrewsBrewIdCloneRoute =
  AuthLayoutDrinksBrewsBrewIdCloneRouteImport.update({
    id: '/drinks/brews/$brewId/clone',
    path: '/drinks/brews/$brewId/clone',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRoute =
  AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRouteImport.update({
    id: '/samples/$sampleId',
    path: '/samples/$sampleId',
    getParentRoute: () => AuthLayoutDrinksTastingsTastingIdRoute,
  } as any)
const AuthLayoutDrinksEspressoEspressoIdDecentEditRoute =
  AuthLayoutDrinksEspressoEspressoIdDecentEditRouteImport.update({
    id: '/drinks/espresso/$espressoId/decent/edit',
    path: '/drinks/espresso/$espressoId/decent/edit',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutDrinksEspressoEspressoIdDecentAddRoute =
  AuthLayoutDrinksEspressoEspressoIdDecentAddRouteImport.update({
    id: '/drinks/espresso/$espressoId/decent/add',
    path: '/drinks/espresso/$espressoId/decent/add',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthLayoutIndexRoute
  '/login': typeof PublicLoginRoute
  '/api/decent-shots': typeof ApiDecentShotsRoute
  '/api/feature-flags': typeof ApiFeatureFlagsRoute
  '/ai': typeof AuthLayoutAiRoute
  '/decent-upload': typeof AuthLayoutDecentUploadRoute
  '/design-library': typeof AuthLayoutDesignLibraryRoute
  '/settings': typeof AuthLayoutSettingsRoute
  '/beans/add': typeof AuthLayoutBeansAddRoute
  '/beans/': typeof AuthLayoutBeansIndexRoute
  '/drinks/': typeof AuthLayoutDrinksIndexRoute
  '/beans/$beansId/clone': typeof AuthLayoutBeansBeansIdCloneRoute
  '/beans/$beansId/edit': typeof AuthLayoutBeansBeansIdEditRoute
  '/drinks/brews/add': typeof AuthLayoutDrinksBrewsAddRoute
  '/drinks/espresso/add': typeof AuthLayoutDrinksEspressoAddRoute
  '/drinks/tastings/$tastingId': typeof AuthLayoutDrinksTastingsTastingIdRouteWithChildren
  '/drinks/brews/table': typeof AuthLayoutFullDrinksBrewsTableRoute
  '/beans/$beansId/': typeof AuthLayoutBeansBeansIdIndexRoute
  '/drinks/brews/': typeof AuthLayoutDrinksBrewsIndexRoute
  '/drinks/espresso/': typeof AuthLayoutDrinksEspressoIndexRoute
  '/drinks/tastings/': typeof AuthLayoutDrinksTastingsIndexRoute
  '/drinks/brews/$brewId/clone': typeof AuthLayoutDrinksBrewsBrewIdCloneRoute
  '/drinks/brews/$brewId/edit': typeof AuthLayoutDrinksBrewsBrewIdEditRoute
  '/drinks/brews/$brewId/outcome': typeof AuthLayoutDrinksBrewsBrewIdOutcomeRoute
  '/drinks/espresso/$espressoId/clone': typeof AuthLayoutDrinksEspressoEspressoIdCloneRoute
  '/drinks/espresso/$espressoId/edit': typeof AuthLayoutDrinksEspressoEspressoIdEditRoute
  '/drinks/espresso/$espressoId/outcome': typeof AuthLayoutDrinksEspressoEspressoIdOutcomeRoute
  '/drinks/brews/$brewId/': typeof AuthLayoutDrinksBrewsBrewIdIndexRoute
  '/drinks/espresso/$espressoId/': typeof AuthLayoutDrinksEspressoEspressoIdIndexRoute
  '/drinks/tastings/$tastingId/': typeof AuthLayoutDrinksTastingsTastingIdIndexRoute
  '/drinks/espresso/$espressoId/decent/add': typeof AuthLayoutDrinksEspressoEspressoIdDecentAddRoute
  '/drinks/espresso/$espressoId/decent/edit': typeof AuthLayoutDrinksEspressoEspressoIdDecentEditRoute
  '/drinks/tastings/$tastingId/samples/$sampleId': typeof AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthLayoutIndexRoute
  '/login': typeof PublicLoginRoute
  '/api/decent-shots': typeof ApiDecentShotsRoute
  '/api/feature-flags': typeof ApiFeatureFlagsRoute
  '/ai': typeof AuthLayoutAiRoute
  '/decent-upload': typeof AuthLayoutDecentUploadRoute
  '/design-library': typeof AuthLayoutDesignLibraryRoute
  '/settings': typeof AuthLayoutSettingsRoute
  '/beans/add': typeof AuthLayoutBeansAddRoute
  '/beans': typeof AuthLayoutBeansIndexRoute
  '/drinks': typeof AuthLayoutDrinksIndexRoute
  '/beans/$beansId/clone': typeof AuthLayoutBeansBeansIdCloneRoute
  '/beans/$beansId/edit': typeof AuthLayoutBeansBeansIdEditRoute
  '/drinks/brews/add': typeof AuthLayoutDrinksBrewsAddRoute
  '/drinks/espresso/add': typeof AuthLayoutDrinksEspressoAddRoute
  '/drinks/brews/table': typeof AuthLayoutFullDrinksBrewsTableRoute
  '/beans/$beansId': typeof AuthLayoutBeansBeansIdIndexRoute
  '/drinks/brews': typeof AuthLayoutDrinksBrewsIndexRoute
  '/drinks/espresso': typeof AuthLayoutDrinksEspressoIndexRoute
  '/drinks/tastings': typeof AuthLayoutDrinksTastingsIndexRoute
  '/drinks/brews/$brewId/clone': typeof AuthLayoutDrinksBrewsBrewIdCloneRoute
  '/drinks/brews/$brewId/edit': typeof AuthLayoutDrinksBrewsBrewIdEditRoute
  '/drinks/brews/$brewId/outcome': typeof AuthLayoutDrinksBrewsBrewIdOutcomeRoute
  '/drinks/espresso/$espressoId/clone': typeof AuthLayoutDrinksEspressoEspressoIdCloneRoute
  '/drinks/espresso/$espressoId/edit': typeof AuthLayoutDrinksEspressoEspressoIdEditRoute
  '/drinks/espresso/$espressoId/outcome': typeof AuthLayoutDrinksEspressoEspressoIdOutcomeRoute
  '/drinks/brews/$brewId': typeof AuthLayoutDrinksBrewsBrewIdIndexRoute
  '/drinks/espresso/$espressoId': typeof AuthLayoutDrinksEspressoEspressoIdIndexRoute
  '/drinks/tastings/$tastingId': typeof AuthLayoutDrinksTastingsTastingIdIndexRoute
  '/drinks/espresso/$espressoId/decent/add': typeof AuthLayoutDrinksEspressoEspressoIdDecentAddRoute
  '/drinks/espresso/$espressoId/decent/edit': typeof AuthLayoutDrinksEspressoEspressoIdDecentEditRoute
  '/drinks/tastings/$tastingId/samples/$sampleId': typeof AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_auth/_layoutFull': typeof AuthLayoutFullRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/api/decent-shots': typeof ApiDecentShotsRoute
  '/api/feature-flags': typeof ApiFeatureFlagsRoute
  '/_auth/_layout/ai': typeof AuthLayoutAiRoute
  '/_auth/_layout/decent-upload': typeof AuthLayoutDecentUploadRoute
  '/_auth/_layout/design-library': typeof AuthLayoutDesignLibraryRoute
  '/_auth/_layout/settings': typeof AuthLayoutSettingsRoute
  '/_auth/_layout/': typeof AuthLayoutIndexRoute
  '/_auth/_layout/beans/add': typeof AuthLayoutBeansAddRoute
  '/_auth/_layout/beans/': typeof AuthLayoutBeansIndexRoute
  '/_auth/_layout/drinks/': typeof AuthLayoutDrinksIndexRoute
  '/_auth/_layout/beans/$beansId/clone': typeof AuthLayoutBeansBeansIdCloneRoute
  '/_auth/_layout/beans/$beansId/edit': typeof AuthLayoutBeansBeansIdEditRoute
  '/_auth/_layout/drinks/brews/add': typeof AuthLayoutDrinksBrewsAddRoute
  '/_auth/_layout/drinks/espresso/add': typeof AuthLayoutDrinksEspressoAddRoute
  '/_auth/_layout/drinks/tastings/$tastingId': typeof AuthLayoutDrinksTastingsTastingIdRouteWithChildren
  '/_auth/_layoutFull/drinks/brews/table': typeof AuthLayoutFullDrinksBrewsTableRoute
  '/_auth/_layout/beans/$beansId/': typeof AuthLayoutBeansBeansIdIndexRoute
  '/_auth/_layout/drinks/brews/': typeof AuthLayoutDrinksBrewsIndexRoute
  '/_auth/_layout/drinks/espresso/': typeof AuthLayoutDrinksEspressoIndexRoute
  '/_auth/_layout/drinks/tastings/': typeof AuthLayoutDrinksTastingsIndexRoute
  '/_auth/_layout/drinks/brews/$brewId/clone': typeof AuthLayoutDrinksBrewsBrewIdCloneRoute
  '/_auth/_layout/drinks/brews/$brewId/edit': typeof AuthLayoutDrinksBrewsBrewIdEditRoute
  '/_auth/_layout/drinks/brews/$brewId/outcome': typeof AuthLayoutDrinksBrewsBrewIdOutcomeRoute
  '/_auth/_layout/drinks/espresso/$espressoId/clone': typeof AuthLayoutDrinksEspressoEspressoIdCloneRoute
  '/_auth/_layout/drinks/espresso/$espressoId/edit': typeof AuthLayoutDrinksEspressoEspressoIdEditRoute
  '/_auth/_layout/drinks/espresso/$espressoId/outcome': typeof AuthLayoutDrinksEspressoEspressoIdOutcomeRoute
  '/_auth/_layout/drinks/brews/$brewId/': typeof AuthLayoutDrinksBrewsBrewIdIndexRoute
  '/_auth/_layout/drinks/espresso/$espressoId/': typeof AuthLayoutDrinksEspressoEspressoIdIndexRoute
  '/_auth/_layout/drinks/tastings/$tastingId/': typeof AuthLayoutDrinksTastingsTastingIdIndexRoute
  '/_auth/_layout/drinks/espresso/$espressoId/decent/add': typeof AuthLayoutDrinksEspressoEspressoIdDecentAddRoute
  '/_auth/_layout/drinks/espresso/$espressoId/decent/edit': typeof AuthLayoutDrinksEspressoEspressoIdDecentEditRoute
  '/_auth/_layout/drinks/tastings/$tastingId/samples/$sampleId': typeof AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/decent-shots'
    | '/api/feature-flags'
    | '/ai'
    | '/decent-upload'
    | '/design-library'
    | '/settings'
    | '/beans/add'
    | '/beans/'
    | '/drinks/'
    | '/beans/$beansId/clone'
    | '/beans/$beansId/edit'
    | '/drinks/brews/add'
    | '/drinks/espresso/add'
    | '/drinks/tastings/$tastingId'
    | '/drinks/brews/table'
    | '/beans/$beansId/'
    | '/drinks/brews/'
    | '/drinks/espresso/'
    | '/drinks/tastings/'
    | '/drinks/brews/$brewId/clone'
    | '/drinks/brews/$brewId/edit'
    | '/drinks/brews/$brewId/outcome'
    | '/drinks/espresso/$espressoId/clone'
    | '/drinks/espresso/$espressoId/edit'
    | '/drinks/espresso/$espressoId/outcome'
    | '/drinks/brews/$brewId/'
    | '/drinks/espresso/$espressoId/'
    | '/drinks/tastings/$tastingId/'
    | '/drinks/espresso/$espressoId/decent/add'
    | '/drinks/espresso/$espressoId/decent/edit'
    | '/drinks/tastings/$tastingId/samples/$sampleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/decent-shots'
    | '/api/feature-flags'
    | '/ai'
    | '/decent-upload'
    | '/design-library'
    | '/settings'
    | '/beans/add'
    | '/beans'
    | '/drinks'
    | '/beans/$beansId/clone'
    | '/beans/$beansId/edit'
    | '/drinks/brews/add'
    | '/drinks/espresso/add'
    | '/drinks/brews/table'
    | '/beans/$beansId'
    | '/drinks/brews'
    | '/drinks/espresso'
    | '/drinks/tastings'
    | '/drinks/brews/$brewId/clone'
    | '/drinks/brews/$brewId/edit'
    | '/drinks/brews/$brewId/outcome'
    | '/drinks/espresso/$espressoId/clone'
    | '/drinks/espresso/$espressoId/edit'
    | '/drinks/espresso/$espressoId/outcome'
    | '/drinks/brews/$brewId'
    | '/drinks/espresso/$espressoId'
    | '/drinks/tastings/$tastingId'
    | '/drinks/espresso/$espressoId/decent/add'
    | '/drinks/espresso/$espressoId/decent/edit'
    | '/drinks/tastings/$tastingId/samples/$sampleId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/_layout'
    | '/_auth/_layoutFull'
    | '/_public/login'
    | '/api/decent-shots'
    | '/api/feature-flags'
    | '/_auth/_layout/ai'
    | '/_auth/_layout/decent-upload'
    | '/_auth/_layout/design-library'
    | '/_auth/_layout/settings'
    | '/_auth/_layout/'
    | '/_auth/_layout/beans/add'
    | '/_auth/_layout/beans/'
    | '/_auth/_layout/drinks/'
    | '/_auth/_layout/beans/$beansId/clone'
    | '/_auth/_layout/beans/$beansId/edit'
    | '/_auth/_layout/drinks/brews/add'
    | '/_auth/_layout/drinks/espresso/add'
    | '/_auth/_layout/drinks/tastings/$tastingId'
    | '/_auth/_layoutFull/drinks/brews/table'
    | '/_auth/_layout/beans/$beansId/'
    | '/_auth/_layout/drinks/brews/'
    | '/_auth/_layout/drinks/espresso/'
    | '/_auth/_layout/drinks/tastings/'
    | '/_auth/_layout/drinks/brews/$brewId/clone'
    | '/_auth/_layout/drinks/brews/$brewId/edit'
    | '/_auth/_layout/drinks/brews/$brewId/outcome'
    | '/_auth/_layout/drinks/espresso/$espressoId/clone'
    | '/_auth/_layout/drinks/espresso/$espressoId/edit'
    | '/_auth/_layout/drinks/espresso/$espressoId/outcome'
    | '/_auth/_layout/drinks/brews/$brewId/'
    | '/_auth/_layout/drinks/espresso/$espressoId/'
    | '/_auth/_layout/drinks/tastings/$tastingId/'
    | '/_auth/_layout/drinks/espresso/$espressoId/decent/add'
    | '/_auth/_layout/drinks/espresso/$espressoId/decent/edit'
    | '/_auth/_layout/drinks/tastings/$tastingId/samples/$sampleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiDecentShotsRoute: typeof ApiDecentShotsRoute
  ApiFeatureFlagsRoute: typeof ApiFeatureFlagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feature-flags': {
      id: '/api/feature-flags'
      path: '/api/feature-flags'
      fullPath: '/api/feature-flags'
      preLoaderRoute: typeof ApiFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decent-shots': {
      id: '/api/decent-shots'
      path: '/api/decent-shots'
      fullPath: '/api/decent-shots'
      preLoaderRoute: typeof ApiDecentShotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/_layoutFull': {
      id: '/_auth/_layoutFull'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutFullRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_layout/': {
      id: '/_auth/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/settings': {
      id: '/_auth/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthLayoutSettingsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/design-library': {
      id: '/_auth/_layout/design-library'
      path: '/design-library'
      fullPath: '/design-library'
      preLoaderRoute: typeof AuthLayoutDesignLibraryRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/decent-upload': {
      id: '/_auth/_layout/decent-upload'
      path: '/decent-upload'
      fullPath: '/decent-upload'
      preLoaderRoute: typeof AuthLayoutDecentUploadRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/ai': {
      id: '/_auth/_layout/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthLayoutAiRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/': {
      id: '/_auth/_layout/drinks/'
      path: '/drinks'
      fullPath: '/drinks/'
      preLoaderRoute: typeof AuthLayoutDrinksIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/beans/': {
      id: '/_auth/_layout/beans/'
      path: '/beans'
      fullPath: '/beans/'
      preLoaderRoute: typeof AuthLayoutBeansIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/beans/add': {
      id: '/_auth/_layout/beans/add'
      path: '/beans/add'
      fullPath: '/beans/add'
      preLoaderRoute: typeof AuthLayoutBeansAddRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/tastings/': {
      id: '/_auth/_layout/drinks/tastings/'
      path: '/drinks/tastings'
      fullPath: '/drinks/tastings/'
      preLoaderRoute: typeof AuthLayoutDrinksTastingsIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/espresso/': {
      id: '/_auth/_layout/drinks/espresso/'
      path: '/drinks/espresso'
      fullPath: '/drinks/espresso/'
      preLoaderRoute: typeof AuthLayoutDrinksEspressoIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/brews/': {
      id: '/_auth/_layout/drinks/brews/'
      path: '/drinks/brews'
      fullPath: '/drinks/brews/'
      preLoaderRoute: typeof AuthLayoutDrinksBrewsIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/beans/$beansId/': {
      id: '/_auth/_layout/beans/$beansId/'
      path: '/beans/$beansId'
      fullPath: '/beans/$beansId/'
      preLoaderRoute: typeof AuthLayoutBeansBeansIdIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layoutFull/drinks/brews/table': {
      id: '/_auth/_layoutFull/drinks/brews/table'
      path: '/drinks/brews/table'
      fullPath: '/drinks/brews/table'
      preLoaderRoute: typeof AuthLayoutFullDrinksBrewsTableRouteImport
      parentRoute: typeof AuthLayoutFullRoute
    }
    '/_auth/_layout/drinks/tastings/$tastingId': {
      id: '/_auth/_layout/drinks/tastings/$tastingId'
      path: '/drinks/tastings/$tastingId'
      fullPath: '/drinks/tastings/$tastingId'
      preLoaderRoute: typeof AuthLayoutDrinksTastingsTastingIdRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/espresso/add': {
      id: '/_auth/_layout/drinks/espresso/add'
      path: '/drinks/espresso/add'
      fullPath: '/drinks/espresso/add'
      preLoaderRoute: typeof AuthLayoutDrinksEspressoAddRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/brews/add': {
      id: '/_auth/_layout/drinks/brews/add'
      path: '/drinks/brews/add'
      fullPath: '/drinks/brews/add'
      preLoaderRoute: typeof AuthLayoutDrinksBrewsAddRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/beans/$beansId/edit': {
      id: '/_auth/_layout/beans/$beansId/edit'
      path: '/beans/$beansId/edit'
      fullPath: '/beans/$beansId/edit'
      preLoaderRoute: typeof AuthLayoutBeansBeansIdEditRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/beans/$beansId/clone': {
      id: '/_auth/_layout/beans/$beansId/clone'
      path: '/beans/$beansId/clone'
      fullPath: '/beans/$beansId/clone'
      preLoaderRoute: typeof AuthLayoutBeansBeansIdCloneRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/tastings/$tastingId/': {
      id: '/_auth/_layout/drinks/tastings/$tastingId/'
      path: '/'
      fullPath: '/drinks/tastings/$tastingId/'
      preLoaderRoute: typeof AuthLayoutDrinksTastingsTastingIdIndexRouteImport
      parentRoute: typeof AuthLayoutDrinksTastingsTastingIdRoute
    }
    '/_auth/_layout/drinks/espresso/$espressoId/': {
      id: '/_auth/_layout/drinks/espresso/$espressoId/'
      path: '/drinks/espresso/$espressoId'
      fullPath: '/drinks/espresso/$espressoId/'
      preLoaderRoute: typeof AuthLayoutDrinksEspressoEspressoIdIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/brews/$brewId/': {
      id: '/_auth/_layout/drinks/brews/$brewId/'
      path: '/drinks/brews/$brewId'
      fullPath: '/drinks/brews/$brewId/'
      preLoaderRoute: typeof AuthLayoutDrinksBrewsBrewIdIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/espresso/$espressoId/outcome': {
      id: '/_auth/_layout/drinks/espresso/$espressoId/outcome'
      path: '/drinks/espresso/$espressoId/outcome'
      fullPath: '/drinks/espresso/$espressoId/outcome'
      preLoaderRoute: typeof AuthLayoutDrinksEspressoEspressoIdOutcomeRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/espresso/$espressoId/edit': {
      id: '/_auth/_layout/drinks/espresso/$espressoId/edit'
      path: '/drinks/espresso/$espressoId/edit'
      fullPath: '/drinks/espresso/$espressoId/edit'
      preLoaderRoute: typeof AuthLayoutDrinksEspressoEspressoIdEditRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/espresso/$espressoId/clone': {
      id: '/_auth/_layout/drinks/espresso/$espressoId/clone'
      path: '/drinks/espresso/$espressoId/clone'
      fullPath: '/drinks/espresso/$espressoId/clone'
      preLoaderRoute: typeof AuthLayoutDrinksEspressoEspressoIdCloneRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/brews/$brewId/outcome': {
      id: '/_auth/_layout/drinks/brews/$brewId/outcome'
      path: '/drinks/brews/$brewId/outcome'
      fullPath: '/drinks/brews/$brewId/outcome'
      preLoaderRoute: typeof AuthLayoutDrinksBrewsBrewIdOutcomeRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/brews/$brewId/edit': {
      id: '/_auth/_layout/drinks/brews/$brewId/edit'
      path: '/drinks/brews/$brewId/edit'
      fullPath: '/drinks/brews/$brewId/edit'
      preLoaderRoute: typeof AuthLayoutDrinksBrewsBrewIdEditRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/brews/$brewId/clone': {
      id: '/_auth/_layout/drinks/brews/$brewId/clone'
      path: '/drinks/brews/$brewId/clone'
      fullPath: '/drinks/brews/$brewId/clone'
      preLoaderRoute: typeof AuthLayoutDrinksBrewsBrewIdCloneRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/tastings/$tastingId/samples/$sampleId': {
      id: '/_auth/_layout/drinks/tastings/$tastingId/samples/$sampleId'
      path: '/samples/$sampleId'
      fullPath: '/drinks/tastings/$tastingId/samples/$sampleId'
      preLoaderRoute: typeof AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRouteImport
      parentRoute: typeof AuthLayoutDrinksTastingsTastingIdRoute
    }
    '/_auth/_layout/drinks/espresso/$espressoId/decent/edit': {
      id: '/_auth/_layout/drinks/espresso/$espressoId/decent/edit'
      path: '/drinks/espresso/$espressoId/decent/edit'
      fullPath: '/drinks/espresso/$espressoId/decent/edit'
      preLoaderRoute: typeof AuthLayoutDrinksEspressoEspressoIdDecentEditRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/drinks/espresso/$espressoId/decent/add': {
      id: '/_auth/_layout/drinks/espresso/$espressoId/decent/add'
      path: '/drinks/espresso/$espressoId/decent/add'
      fullPath: '/drinks/espresso/$espressoId/decent/add'
      preLoaderRoute: typeof AuthLayoutDrinksEspressoEspressoIdDecentAddRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutDrinksTastingsTastingIdRouteChildren {
  AuthLayoutDrinksTastingsTastingIdIndexRoute: typeof AuthLayoutDrinksTastingsTastingIdIndexRoute
  AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRoute: typeof AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRoute
}

const AuthLayoutDrinksTastingsTastingIdRouteChildren: AuthLayoutDrinksTastingsTastingIdRouteChildren =
  {
    AuthLayoutDrinksTastingsTastingIdIndexRoute:
      AuthLayoutDrinksTastingsTastingIdIndexRoute,
    AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRoute:
      AuthLayoutDrinksTastingsTastingIdSamplesSampleIdRoute,
  }

const AuthLayoutDrinksTastingsTastingIdRouteWithChildren =
  AuthLayoutDrinksTastingsTastingIdRoute._addFileChildren(
    AuthLayoutDrinksTastingsTastingIdRouteChildren,
  )

interface AuthLayoutRouteChildren {
  AuthLayoutAiRoute: typeof AuthLayoutAiRoute
  AuthLayoutDecentUploadRoute: typeof AuthLayoutDecentUploadRoute
  AuthLayoutDesignLibraryRoute: typeof AuthLayoutDesignLibraryRoute
  AuthLayoutSettingsRoute: typeof AuthLayoutSettingsRoute
  AuthLayoutIndexRoute: typeof AuthLayoutIndexRoute
  AuthLayoutBeansAddRoute: typeof AuthLayoutBeansAddRoute
  AuthLayoutBeansIndexRoute: typeof AuthLayoutBeansIndexRoute
  AuthLayoutDrinksIndexRoute: typeof AuthLayoutDrinksIndexRoute
  AuthLayoutBeansBeansIdCloneRoute: typeof AuthLayoutBeansBeansIdCloneRoute
  AuthLayoutBeansBeansIdEditRoute: typeof AuthLayoutBeansBeansIdEditRoute
  AuthLayoutDrinksBrewsAddRoute: typeof AuthLayoutDrinksBrewsAddRoute
  AuthLayoutDrinksEspressoAddRoute: typeof AuthLayoutDrinksEspressoAddRoute
  AuthLayoutDrinksTastingsTastingIdRoute: typeof AuthLayoutDrinksTastingsTastingIdRouteWithChildren
  AuthLayoutBeansBeansIdIndexRoute: typeof AuthLayoutBeansBeansIdIndexRoute
  AuthLayoutDrinksBrewsIndexRoute: typeof AuthLayoutDrinksBrewsIndexRoute
  AuthLayoutDrinksEspressoIndexRoute: typeof AuthLayoutDrinksEspressoIndexRoute
  AuthLayoutDrinksTastingsIndexRoute: typeof AuthLayoutDrinksTastingsIndexRoute
  AuthLayoutDrinksBrewsBrewIdCloneRoute: typeof AuthLayoutDrinksBrewsBrewIdCloneRoute
  AuthLayoutDrinksBrewsBrewIdEditRoute: typeof AuthLayoutDrinksBrewsBrewIdEditRoute
  AuthLayoutDrinksBrewsBrewIdOutcomeRoute: typeof AuthLayoutDrinksBrewsBrewIdOutcomeRoute
  AuthLayoutDrinksEspressoEspressoIdCloneRoute: typeof AuthLayoutDrinksEspressoEspressoIdCloneRoute
  AuthLayoutDrinksEspressoEspressoIdEditRoute: typeof AuthLayoutDrinksEspressoEspressoIdEditRoute
  AuthLayoutDrinksEspressoEspressoIdOutcomeRoute: typeof AuthLayoutDrinksEspressoEspressoIdOutcomeRoute
  AuthLayoutDrinksBrewsBrewIdIndexRoute: typeof AuthLayoutDrinksBrewsBrewIdIndexRoute
  AuthLayoutDrinksEspressoEspressoIdIndexRoute: typeof AuthLayoutDrinksEspressoEspressoIdIndexRoute
  AuthLayoutDrinksEspressoEspressoIdDecentAddRoute: typeof AuthLayoutDrinksEspressoEspressoIdDecentAddRoute
  AuthLayoutDrinksEspressoEspressoIdDecentEditRoute: typeof AuthLayoutDrinksEspressoEspressoIdDecentEditRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAiRoute: AuthLayoutAiRoute,
  AuthLayoutDecentUploadRoute: AuthLayoutDecentUploadRoute,
  AuthLayoutDesignLibraryRoute: AuthLayoutDesignLibraryRoute,
  AuthLayoutSettingsRoute: AuthLayoutSettingsRoute,
  AuthLayoutIndexRoute: AuthLayoutIndexRoute,
  AuthLayoutBeansAddRoute: AuthLayoutBeansAddRoute,
  AuthLayoutBeansIndexRoute: AuthLayoutBeansIndexRoute,
  AuthLayoutDrinksIndexRoute: AuthLayoutDrinksIndexRoute,
  AuthLayoutBeansBeansIdCloneRoute: AuthLayoutBeansBeansIdCloneRoute,
  AuthLayoutBeansBeansIdEditRoute: AuthLayoutBeansBeansIdEditRoute,
  AuthLayoutDrinksBrewsAddRoute: AuthLayoutDrinksBrewsAddRoute,
  AuthLayoutDrinksEspressoAddRoute: AuthLayoutDrinksEspressoAddRoute,
  AuthLayoutDrinksTastingsTastingIdRoute:
    AuthLayoutDrinksTastingsTastingIdRouteWithChildren,
  AuthLayoutBeansBeansIdIndexRoute: AuthLayoutBeansBeansIdIndexRoute,
  AuthLayoutDrinksBrewsIndexRoute: AuthLayoutDrinksBrewsIndexRoute,
  AuthLayoutDrinksEspressoIndexRoute: AuthLayoutDrinksEspressoIndexRoute,
  AuthLayoutDrinksTastingsIndexRoute: AuthLayoutDrinksTastingsIndexRoute,
  AuthLayoutDrinksBrewsBrewIdCloneRoute: AuthLayoutDrinksBrewsBrewIdCloneRoute,
  AuthLayoutDrinksBrewsBrewIdEditRoute: AuthLayoutDrinksBrewsBrewIdEditRoute,
  AuthLayoutDrinksBrewsBrewIdOutcomeRoute:
    AuthLayoutDrinksBrewsBrewIdOutcomeRoute,
  AuthLayoutDrinksEspressoEspressoIdCloneRoute:
    AuthLayoutDrinksEspressoEspressoIdCloneRoute,
  AuthLayoutDrinksEspressoEspressoIdEditRoute:
    AuthLayoutDrinksEspressoEspressoIdEditRoute,
  AuthLayoutDrinksEspressoEspressoIdOutcomeRoute:
    AuthLayoutDrinksEspressoEspressoIdOutcomeRoute,
  AuthLayoutDrinksBrewsBrewIdIndexRoute: AuthLayoutDrinksBrewsBrewIdIndexRoute,
  AuthLayoutDrinksEspressoEspressoIdIndexRoute:
    AuthLayoutDrinksEspressoEspressoIdIndexRoute,
  AuthLayoutDrinksEspressoEspressoIdDecentAddRoute:
    AuthLayoutDrinksEspressoEspressoIdDecentAddRoute,
  AuthLayoutDrinksEspressoEspressoIdDecentEditRoute:
    AuthLayoutDrinksEspressoEspressoIdDecentEditRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthLayoutFullRouteChildren {
  AuthLayoutFullDrinksBrewsTableRoute: typeof AuthLayoutFullDrinksBrewsTableRoute
}

const AuthLayoutFullRouteChildren: AuthLayoutFullRouteChildren = {
  AuthLayoutFullDrinksBrewsTableRoute: AuthLayoutFullDrinksBrewsTableRoute,
}

const AuthLayoutFullRouteWithChildren = AuthLayoutFullRoute._addFileChildren(
  AuthLayoutFullRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AuthLayoutFullRoute: typeof AuthLayoutFullRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AuthLayoutFullRoute: AuthLayoutFullRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiDecentShotsRoute: ApiDecentShotsRoute,
  ApiFeatureFlagsRoute: ApiFeatureFlagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
